services:
  - type: web
    name: shopmanstore
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MP_TOKEN
        value: APP_USR-5802293204482723-111823-41d8e3354a2e15c8dbc4802b59524b0d-3001373888
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: shopmanstore-db
          property: connectionString
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_APP_PASSWORD
        sync: false
      - key: BASE_URL
        sync: false
      - key: WHATSAPP_PHONE
        value: "5491122549995"
      - key: WHATSAPP_ENABLED
        value: "true"

databases:
  - name: shopmanstore-db
    databaseName: shopmanstore
    user: shopmanstore
